/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux. MIT License.
 */
package com.retromod.core;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Converts a Fabric AccessWidener into a NeoForge/Forge AccessTransformer
 * (META-INF/accesstransformer.cfg).
 *
 * <p>A Fabric-authored (or cross-loader) mod widens Minecraft members with an
 * {@code .accesswidener}; a NeoForge/Forge host cannot read that format and
 * instead consumes an AccessTransformer. Rather than dropping the widening
 * outright (which silently strips a real capability), we translate it so the
 * mod keeps its widened access on the target loader.
 *
 * <p>The AW -> AT modifier table is adapted from Sinytra Connector (MIT)'s
 * {@code AccessWidenerTransformer}:
 * <ul>
 *   <li>class:  {@code accessible} -> {@code public},   {@code extendable} -> {@code public-f}</li>
 *   <li>method: {@code accessible} -> {@code public},   {@code extendable} -> {@code protected-f}</li>
 *   <li>field:  {@code accessible} -> {@code public},   {@code mutable}    -> {@code public-f}</li>
 * </ul>
 * The {@code -f} suffix removes the {@code final} modifier; {@code extendable}
 * on a method must keep it overridable (so {@code protected-f}), while
 * {@code extendable} on a class must keep it subclassable (so {@code public-f}).
 *
 * <p>AccessWidener uses internal class names ({@code net/minecraft/Foo}) and a
 * space between a method name and its descriptor ({@code bar (I)V}). An
 * AccessTransformer uses dotted class names ({@code net.minecraft.Foo}), joins
 * a method name to its descriptor ({@code bar(I)V}), and lists a field by name
 * only.
 *
 * <p>This converter does NO name remapping: it only reshapes the format. It is
 * therefore only sound on input whose names already match the target runtime,
 * i.e. an AW whose header namespace is {@code named}/{@code official} (or absent).
 * An {@code intermediary}-namespace AW (a Fabric-authored cross-loader mod ships
 * {@code class_1234}/{@code method_5678}) would emit an AT referencing classes
 * that do not exist on NeoForge/Forge, producing an unresolvable AT that breaks a
 * mod which previously loaded once the AW was simply deleted. So {@link #convert}
 * refuses an intermediary-namespace AW and returns an empty result, leaving the
 * caller to just delete the AW as before (the NeoForge/Forge path never remaps
 * intermediary names, unlike the Fabric path).
 */
final class AccessWidenerToAtConverter {

    private AccessWidenerToAtConverter() {
    }

    /**
     * Translate AccessWidener text into AccessTransformer text.
     *
     * @return the {@code accesstransformer.cfg} body, or an empty string if the
     *         input yielded no translatable directives
     */
    static String convert(String accessWidenerText) {
        if (accessWidenerText == null || accessWidenerText.isBlank()) {
            return "";
        }

        // Refuse an intermediary-namespace AW: this converter does not remap names,
        // so emitting an AT from class_XXXX/method_XXXX would reference classes absent
        // on the NeoForge/Forge runtime. Fall back to deleting the AW (empty result).
        if (isIntermediaryNamespace(accessWidenerText)) {
            return "";
        }

        List<String> out = new ArrayList<>();
        out.add("# Generated by Retromod from a Fabric access widener.");
        out.add("# AW -> AT modifier table adapted from Sinytra Connector (MIT).");

        // Owners that get their own explicit class directive: don't also emit an implicit
        // owner line for them (their explicit line already widens the class, possibly higher).
        java.util.Set<String> explicitClassOwners = new java.util.LinkedHashSet<>();
        // Owners of a member directive that need an implicit `public <owner>` (AW widens the
        // owning class to public whenever a member is made accessible/extendable/mutable, a
        // documented AW semantic AT has no rule for). Deduplicated, insertion-ordered.
        java.util.Set<String> implicitClassOwners = new java.util.LinkedHashSet<>();

        String[] lines = accessWidenerText.split("\n");
        int emitted = 0;

        for (int i = 0; i < lines.length; i++) {
            String raw = lines[i];
            // Strip trailing comments (AW allows `#` line comments).
            int hash = raw.indexOf('#');
            String line = (hash >= 0 ? raw.substring(0, hash) : raw).trim();

            if (line.isEmpty()) {
                continue;
            }

            // The first non-blank line is the header:
            //   accessWidener v2 named
            if (i == 0 || line.toLowerCase(Locale.ROOT).startsWith("accesswidener")) {
                if (line.toLowerCase(Locale.ROOT).startsWith("accesswidener")) {
                    continue;
                }
            }

            String at = convertDirective(line);
            if (at != null) {
                out.add(at);
                emitted++;

                String owner = directiveOwner(line);
                if (isClassDirective(line)) {
                    if (owner != null) explicitClassOwners.add(owner);
                } else if (owner != null) {
                    implicitClassOwners.add(owner);
                }
            }
        }

        if (emitted == 0) {
            return "";
        }

        // Emit the implicit owner-widening for member owners lacking an explicit class line,
        // mirroring Connector's AW->AT owner-widening so a package-private owner's widened
        // member is actually reachable cross-package on the target.
        for (String owner : implicitClassOwners) {
            if (!explicitClassOwners.contains(owner)) {
                out.add("public " + owner + " # implicit owner-widening (AW semantics)");
            }
        }

        return String.join("\n", out) + "\n";
    }

    /** True when the (comment-stripped) directive line is a {@code class} directive. */
    private static boolean isClassDirective(String line) {
        String[] parts = line.split("\\s+");
        return parts.length >= 2 && "class".equalsIgnoreCase(parts[1]);
    }

    /**
     * The dotted owner class of a directive, or null if it isn't a well-formed directive.
     * Mirrors the parsing in {@link #convertDirective} without recomputing the modifier.
     */
    private static String directiveOwner(String line) {
        String[] parts = line.split("\\s+");
        return parts.length >= 3 ? dotted(parts[2]) : null;
    }

    /**
     * Convert a single AW directive line into an AT line, or return null when
     * the directive is not translatable (unknown access verb / target type).
     *
     * <p>AW directives are: {@code <access> <type> <owner> [member] [desc]},
     * where {@code <access>} is accessible/extendable/mutable and {@code <type>}
     * is class/method/field. A {@code transitive-} prefix on the access verb is
     * a Fabric-only build-time hint; strip it.
     */
    private static String convertDirective(String line) {
        String[] parts = line.split("\\s+");
        if (parts.length < 3) {
            return null;
        }

        String access = parts[0].toLowerCase(Locale.ROOT);
        if (access.startsWith("transitive-")) {
            access = access.substring("transitive-".length());
        }
        String type = parts[1].toLowerCase(Locale.ROOT);
        String owner = dotted(parts[2]);

        switch (type) {
            case "class": {
                if (parts.length != 3) {
                    return null;
                }
                String modifier = switch (access) {
                    case "accessible" -> "public";
                    case "extendable" -> "public-f"; // stay subclassable, drop final
                    default -> null;
                };
                return modifier == null ? null : modifier + " " + owner;
            }
            case "method": {
                // <access> method <owner> <name> <descriptor>
                if (parts.length != 5) {
                    return null;
                }
                String modifier = switch (access) {
                    case "accessible" -> "public";
                    case "extendable" -> "protected-f"; // stay overridable, drop final
                    default -> null;
                };
                if (modifier == null) {
                    return null;
                }
                String name = parts[3];
                String desc = parts[4];
                return modifier + " " + owner + " " + name + desc;
            }
            case "field": {
                // <access> field <owner> <name> <descriptor>
                if (parts.length != 5) {
                    return null;
                }
                String modifier = switch (access) {
                    case "accessible" -> "public";
                    case "mutable" -> "public-f"; // drop final so the field is writable
                    default -> null;
                };
                if (modifier == null) {
                    return null;
                }
                String name = parts[3];
                return modifier + " " + owner + " " + name;
            }
            default:
                return null;
        }
    }

    /**
     * True when the AW header declares the {@code intermediary} namespace. The header is the
     * first non-blank, non-comment line: {@code accessWidener v2 <namespace>}. A missing or
     * {@code named}/{@code official} namespace is treated as safe to convert.
     */
    private static boolean isIntermediaryNamespace(String accessWidenerText) {
        for (String raw : accessWidenerText.split("\n")) {
            int hash = raw.indexOf('#');
            String line = (hash >= 0 ? raw.substring(0, hash) : raw).trim();
            if (line.isEmpty()) {
                continue;
            }
            if (!line.toLowerCase(Locale.ROOT).startsWith("accesswidener")) {
                return false; // no header (or first content line isn't one): assume named
            }
            String[] parts = line.split("\\s+");
            // accessWidener <version> <namespace>
            return parts.length >= 3 && "intermediary".equalsIgnoreCase(parts[2]);
        }
        return false;
    }

    /** Convert an internal class name (net/minecraft/Foo) to dotted (net.minecraft.Foo). */
    private static String dotted(String internalName) {
        return internalName.replace('/', '.');
    }
}
