/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux. Licensed under MIT License.
 */
package com.retromod.shim.api.fabric;

import com.retromod.core.RetromodTransformer;
import com.retromod.core.VersionShim;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Batch of <b>renamed-SAM event bridges</b> for Fabric API interfaces whose
 * 26.1 successor renamed the functional method - the "lambda trap" class of
 * break, where a plain class redirect makes {@code LambdaMetafactory} throw
 * the moment a mod registers a listener. Every entry was verified against the
 * real fabric-api jars (0.141.4+1.21.11 vs 0.145.4+26.1.2); each synthetic
 * uses the extends + default shape of {@link FabricHudRenderCallbackShim},
 * generated by {@link SamBridgeSynthetics}.
 *
 * <p>Bridged here (old → new, SAM rename):
 * <ul>
 *   <li>{@code ClientWorldEvents} → {@code ClientLevelEvents}
 *       ({@code afterWorldChange} → {@code afterLevelChange}; the holder field
 *       also renamed {@code AFTER_CLIENT_WORLD_CHANGE} →
 *       {@code AFTER_CLIENT_LEVEL_CHANGE}, so the old plain redirect was a
 *       double break: NoSuchFieldError before the lambda trap).</li>
 *   <li>{@code ServerEntityWorldChangeEvents} →
 *       {@code ServerEntityLevelChangeEvents} ({@code afterChangeWorld} →
 *       {@code afterChangeLevel} on both SAMs + both holder fields renamed).
 *       NOTE: the real 1.21.x class lives at {@code entity/event/v1/} - the
 *       previous redirect's {@code event/lifecycle/v1/} source path never
 *       existed, so this event was effectively unbridged; both paths now point
 *       at the synthetic.</li>
 *   <li>{@code LivingEntityFeatureRendererRegistrationCallback} →
 *       {@code LivingEntityRenderLayerRegistrationCallback}
 *       ({@code registerRenderers} → {@code registerLayers}; the
 *       {@code $RegistrationHelper} inner kept its {@code register} SAM name,
 *       so it stays a plain redirect).</li>
 *   <li>{@code DrawItemStackOverlayCallback} →
 *       {@code ExtractItemDecorationsCallback} ({@code onDrawItemStackOverlay}
 *       → {@code onExtractItemDecorations}).</li>
 *   <li>{@code TooltipComponentCallback} → {@code ClientTooltipComponentCallback}
 *       ({@code getComponent} → {@code getClientComponent}; non-void SAM -
 *       previously not bridged at all).</li>
 *   <li>{@code ServerChunkEvents$LevelTypeChange} →
 *       {@code $FullChunkStatusChange} ({@code onChunkLevelTypeChange} →
 *       {@code onFullChunkStatusChange}; the OUTER holder survives, so only
 *       the inner gets a synthetic plus a field redirect
 *       {@code CHUNK_LEVEL_TYPE_CHANGE} → {@code FULL_CHUNK_STATUS_CHANGE}).</li>
 *   <li>{@code LandPathNodeTypesRegistry} → {@code LandPathTypeRegistry}
 *       (static registry: class+method renames; its {@code Static}/{@code
 *       Dynamic} provider SAMs renamed {@code getPathNodeType} →
 *       {@code getPathType} - those two get synthetics; previously not
 *       bridged at all).</li>
 * </ul>
 *
 * <p><b>Gated 26.1+</b> (pitfall #9): every old interface here is alive and
 * working on pre-26.1 hosts, and the synthetics' Mojang-name descriptors only
 * resolve on 26.1.</p>
 *
 * <p><b>STATUS - authored + transform-tested; events need the same in-game
 * pass as the other reflective bridges (they soft-fail to inert).</b></p>
 */
public class FabricRenamedSamBridgesShim implements VersionShim {

    private static final Logger LOGGER = LoggerFactory.getLogger("Retromod");

    private static final String GEN = "com/retromod/generated/legacyevents/";
    private static final String FAPI = "net/fabricmc/fabric/api/";

    @Override public String getShimName() { return "Fabric renamed-SAM event bridges (26.1)"; }
    @Override public String getSourceVersion() { return "0.40.0"; }
    @Override public String getTargetVersion() { return "0.145.0"; }
    @Override public String getModLoaderType() { return "fabric"; }

    @Override
    public void registerRedirects(RetromodTransformer t) {
        if (!com.retromod.core.RetromodVersion.isUnobfuscatedTarget(
                com.retromod.core.RetromodVersion.TARGET_MC_VERSION)) {
            LOGGER.debug("[Retromod] renamed-SAM bridges skipped (host {} < 26.1 - old APIs still present)",
                    com.retromod.core.RetromodVersion.TARGET_MC_VERSION);
            return;
        }

        // ── ClientWorldEvents ───────────────────────────────────────────────
        String cweOld = FAPI + "client/event/lifecycle/v1/ClientWorldEvents";
        String cweNewDot = "net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLevelEvents";
        String cweSynth = GEN + "ClientWorldEvents";
        t.registerSyntheticClass(cweSynth, SamBridgeSynthetics.eventHolder(cweSynth, new String[][]{
                {"AFTER_CLIENT_WORLD_CHANGE", cweNewDot, "AFTER_CLIENT_LEVEL_CHANGE"}
        }));
        t.registerSyntheticClass(cweSynth + "$AfterClientWorldChange", SamBridgeSynthetics.samInterface(
                cweSynth + "$AfterClientWorldChange",
                FAPI + "client/event/lifecycle/v1/ClientLevelEvents$AfterClientLevelChange",
                "afterWorldChange", "afterLevelChange",
                "(Lnet/minecraft/client/Minecraft;Lnet/minecraft/client/multiplayer/ClientLevel;)V",
                null, null));
        t.registerClassRedirect(cweOld, cweSynth);
        t.registerClassRedirect(cweOld + "$AfterClientWorldChange", cweSynth + "$AfterClientWorldChange");

        // ── ServerEntityWorldChangeEvents ───────────────────────────────────
        String sewOld = FAPI + "entity/event/v1/ServerEntityWorldChangeEvents";
        String sewNewDot = "net.fabricmc.fabric.api.entity.event.v1.ServerEntityLevelChangeEvents";
        String sewSynth = GEN + "ServerEntityWorldChangeEvents";
        t.registerSyntheticClass(sewSynth, SamBridgeSynthetics.eventHolder(sewSynth, new String[][]{
                {"AFTER_ENTITY_CHANGE_WORLD", sewNewDot, "AFTER_ENTITY_CHANGE_LEVEL"},
                {"AFTER_PLAYER_CHANGE_WORLD", sewNewDot, "AFTER_PLAYER_CHANGE_LEVEL"}
        }));
        t.registerSyntheticClass(sewSynth + "$AfterEntityChange", SamBridgeSynthetics.samInterface(
                sewSynth + "$AfterEntityChange",
                FAPI + "entity/event/v1/ServerEntityLevelChangeEvents$AfterEntityChange",
                "afterChangeWorld", "afterChangeLevel",
                "(Lnet/minecraft/world/entity/Entity;Lnet/minecraft/world/entity/Entity;"
                        + "Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/server/level/ServerLevel;)V",
                null, null));
        t.registerSyntheticClass(sewSynth + "$AfterPlayerChange", SamBridgeSynthetics.samInterface(
                sewSynth + "$AfterPlayerChange",
                FAPI + "entity/event/v1/ServerEntityLevelChangeEvents$AfterPlayerChange",
                "afterChangeWorld", "afterChangeLevel",
                "(Lnet/minecraft/server/level/ServerPlayer;"
                        + "Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/server/level/ServerLevel;)V",
                null, null));
        // The real 1.21.x path AND the never-existed lifecycle path the old
        // redirect used (kept in case any era of fabric-api had it there).
        t.registerClassRedirect(sewOld, sewSynth);
        t.registerClassRedirect(sewOld + "$AfterEntityChange", sewSynth + "$AfterEntityChange");
        t.registerClassRedirect(sewOld + "$AfterPlayerChange", sewSynth + "$AfterPlayerChange");
        String sewLifecycle = FAPI + "event/lifecycle/v1/ServerEntityWorldChangeEvents";
        t.registerClassRedirect(sewLifecycle, sewSynth);
        t.registerClassRedirect(sewLifecycle + "$AfterEntityChange", sewSynth + "$AfterEntityChange");
        t.registerClassRedirect(sewLifecycle + "$AfterPlayerChange", sewSynth + "$AfterPlayerChange");

        // ── LivingEntityFeatureRendererRegistrationCallback ─────────────────
        String lefOld = FAPI + "client/rendering/v1/LivingEntityFeatureRendererRegistrationCallback";
        String lefNew = FAPI + "client/rendering/v1/LivingEntityRenderLayerRegistrationCallback";
        String lefSynth = GEN + "LivingEntityFeatureRendererRegistrationCallback";
        t.registerSyntheticClass(lefSynth, SamBridgeSynthetics.samInterface(
                lefSynth, lefNew,
                "registerRenderers", "registerLayers",
                "(Lnet/minecraft/world/entity/EntityType;"
                        + "Lnet/minecraft/client/renderer/entity/LivingEntityRenderer;"
                        + "L" + lefNew + "$RegistrationHelper;"
                        + "Lnet/minecraft/client/renderer/entity/EntityRendererProvider$Context;)V",
                lefNew.replace('/', '.'), "EVENT"));
        t.registerClassRedirect(lefOld, lefSynth);
        // Helper inner kept its `register` SAM name - plain redirect is safe.
        t.registerClassRedirect(lefOld + "$RegistrationHelper", lefNew + "$RegistrationHelper");

        // ── DrawItemStackOverlayCallback ────────────────────────────────────
        String disOld = FAPI + "client/rendering/v1/DrawItemStackOverlayCallback";
        String disNew = FAPI + "client/rendering/v1/ExtractItemDecorationsCallback";
        String disSynth = GEN + "DrawItemStackOverlayCallback";
        t.registerSyntheticClass(disSynth, SamBridgeSynthetics.samInterface(
                disSynth, disNew,
                "onDrawItemStackOverlay", "onExtractItemDecorations",
                "(Lnet/minecraft/client/gui/GuiGraphicsExtractor;Lnet/minecraft/client/gui/Font;"
                        + "Lnet/minecraft/world/item/ItemStack;II)V",
                disNew.replace('/', '.'), "EVENT"));
        t.registerClassRedirect(disOld, disSynth);

        // ── TooltipComponentCallback (non-void SAM) ─────────────────────────
        String ttcOld = FAPI + "client/rendering/v1/TooltipComponentCallback";
        String ttcNew = FAPI + "client/rendering/v1/ClientTooltipComponentCallback";
        String ttcSynth = GEN + "TooltipComponentCallback";
        t.registerSyntheticClass(ttcSynth, SamBridgeSynthetics.samInterface(
                ttcSynth, ttcNew,
                "getComponent", "getClientComponent",
                "(Lnet/minecraft/world/inventory/tooltip/TooltipComponent;)"
                        + "Lnet/minecraft/client/gui/screens/inventory/tooltip/ClientTooltipComponent;",
                ttcNew.replace('/', '.'), "EVENT"));
        t.registerClassRedirect(ttcOld, ttcSynth);

        // ── ServerChunkEvents$LevelTypeChange (outer holder survives) ───────
        String sceOuter = FAPI + "event/lifecycle/v1/ServerChunkEvents";
        String sceSynth = GEN + "ServerChunkEvents$LevelTypeChange";
        t.registerSyntheticClass(sceSynth, SamBridgeSynthetics.samInterface(
                sceSynth, sceOuter + "$FullChunkStatusChange",
                "onChunkLevelTypeChange", "onFullChunkStatusChange",
                "(Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/world/level/chunk/LevelChunk;"
                        + "Lnet/minecraft/server/level/FullChunkStatus;Lnet/minecraft/server/level/FullChunkStatus;)V",
                null, null));
        t.registerClassRedirect(sceOuter + "$LevelTypeChange", sceSynth);
        t.registerFieldRedirect(sceOuter, "CHUNK_LEVEL_TYPE_CHANGE", sceOuter, "FULL_CHUNK_STATUS_CHANGE");

        // ── LandPathNodeTypesRegistry → LandPathTypeRegistry ────────────────
        String lpOld = FAPI + "registry/LandPathNodeTypesRegistry";
        String lpNew = FAPI + "registry/LandPathTypeRegistry";
        t.registerClassRedirect(lpOld, lpNew);
        t.registerClassRedirect(lpOld + "$PathNodeTypeProvider", lpNew + "$PathTypeProvider");
        // Provider SAMs renamed getPathNodeType → getPathType - lambda traps.
        t.registerSyntheticClass(GEN + "LandStaticPathProvider", SamBridgeSynthetics.samInterface(
                GEN + "LandStaticPathProvider", lpNew + "$StaticPathTypeProvider",
                "getPathNodeType", "getPathType",
                "(Lnet/minecraft/world/level/block/state/BlockState;Z)"
                        + "Lnet/minecraft/world/level/pathfinder/PathType;",
                null, null));
        t.registerClassRedirect(lpOld + "$StaticPathNodeTypeProvider", GEN + "LandStaticPathProvider");
        t.registerSyntheticClass(GEN + "LandDynamicPathProvider", SamBridgeSynthetics.samInterface(
                GEN + "LandDynamicPathProvider", lpNew + "$DynamicPathTypeProvider",
                "getPathNodeType", "getPathType",
                "(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;"
                        + "Lnet/minecraft/core/BlockPos;Z)Lnet/minecraft/world/level/pathfinder/PathType;",
                null, null));
        t.registerClassRedirect(lpOld + "$DynamicPathNodeTypeProvider", GEN + "LandDynamicPathProvider");
        // Static getters renamed (register/registerDynamic kept their names);
        // keyed on the NEW owner - class redirects run before method redirects.
        t.registerMethodRedirect(
                lpNew, "getPathNodeType",
                "(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;"
                        + "Lnet/minecraft/core/BlockPos;Z)Lnet/minecraft/world/level/pathfinder/PathType;",
                lpNew, "getPathType",
                "(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/BlockGetter;"
                        + "Lnet/minecraft/core/BlockPos;Z)Lnet/minecraft/world/level/pathfinder/PathType;");
        t.registerMethodRedirect(
                lpNew, "getPathNodeTypeProvider",
                "(Lnet/minecraft/world/level/block/Block;)L" + lpNew + "$PathTypeProvider;",
                lpNew, "getPathTypeProvider",
                "(Lnet/minecraft/world/level/block/Block;)L" + lpNew + "$PathTypeProvider;");

        LOGGER.info("[Retromod] Fabric renamed-SAM bridges - ClientWorldEvents, "
                + "ServerEntityWorldChangeEvents, LivingEntityFeatureRendererRegistrationCallback, "
                + "DrawItemStackOverlayCallback, TooltipComponentCallback, "
                + "ServerChunkEvents$LevelTypeChange, LandPathNodeTypesRegistry "
                + "(7 APIs, old SAMs kept; STATUS: needs in-game verification)");
    }
}
