/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux. Licensed under MIT License.
 *
 * TEST STUB of fabric-api's Event class (fabric-api isn't on the test
 * classpath). The generated bridge synthetics declare fields of this type and
 * CHECKCAST against it, so the JVM verifier needs the class present to LOAD
 * them — which is the whole point of the load-verify test: ClassFormatError /
 * VerifyError in generated bytecode must fail in JUnit, not in-game.
 */
package net.fabricmc.fabric.api.event;

public abstract class Event<T> {
    public abstract T invoker();
    public abstract void register(T listener);
}
