/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux
 */
package com.retromod.shim.api.fabric;

import com.retromod.core.RetromodTransformer;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TypeInsnNode;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Structural checks for the synthetic v1 {@code CommandRegistrationCallback}
 * generated by {@link FabricCommandV1Shim}. These verify the bytecode shape that
 * a runtime link depends on - the abstract SAM descriptor, the {@code EVENT} field,
 * and the {@code <clinit>} wiring - so a descriptor typo is caught here rather than
 * only at an in-game launch. (The reflective forwarder itself still needs a 26.1
 * launch to verify end-to-end.)
 */
class FabricCommandV1ShimTest {

    private static final String SYNTH = "com/retromod/generated/legacycmd/CommandRegistrationCallbackV1";
    private static final String OLD_V1 = "net/fabricmc/fabric/api/command/v1/CommandRegistrationCallback";
    private static final String BRIDGE = "com/retromod/shim/api/fabric/embedded/CommandRegistrationV1Bridge";

    private static ClassNode synthetic() {
        ClassNode cn = new ClassNode();
        new ClassReader(FabricCommandV1Shim.generateSamInterface()).accept(cn, 0);
        return cn;
    }

    @Test
    @DisplayName("synthetic is a functional interface with the v1 2-arg register SAM")
    void interfaceWith2ArgSam() {
        ClassNode cn = synthetic();
        assertTrue((cn.access & Opcodes.ACC_INTERFACE) != 0,
                "must be an interface so the mod's lambda can link against it");
        MethodNode sam = cn.methods.stream()
                .filter(m -> m.name.equals("register") && (m.access & Opcodes.ACC_ABSTRACT) != 0)
                .findFirst().orElse(null);
        assertNotNull(sam, "must declare the abstract register SAM");
        // brigadier CommandDispatcher (stable, never remapped) + primitive boolean.
        assertEquals("(Lcom/mojang/brigadier/CommandDispatcher;Z)V", sam.desc,
                "v1 SAM is register(CommandDispatcher, boolean), erased descriptor");
    }

    @Test
    @DisplayName("synthetic carries the static EVENT field the mod reads")
    void hasEventField() {
        FieldNode ev = synthetic().fields.stream()
                .filter(f -> f.name.equals("EVENT")).findFirst().orElse(null);
        assertNotNull(ev, "mod reads CommandRegistrationCallback.EVENT");
        assertEquals("Lnet/fabricmc/fabric/api/event/Event;", ev.desc);
        assertTrue((ev.access & Opcodes.ACC_STATIC) != 0, "EVENT must be static");
        assertTrue((ev.access & Opcodes.ACC_PUBLIC) != 0, "EVENT must be public");
    }

    @Test
    @DisplayName("synthetic <clinit> wires EVENT through the reflective bridge")
    void clinitWiresEvent() {
        MethodNode clinit = synthetic().methods.stream()
                .filter(m -> m.name.equals("<clinit>")).findFirst().orElse(null);
        assertNotNull(clinit, "EVENT needs a static initializer");

        boolean callsInstall = false, castsEvent = false, putsEvent = false;
        for (AbstractInsnNode insn : clinit.instructions) {
            if (insn instanceof MethodInsnNode m
                    && m.owner.equals(BRIDGE)
                    && m.name.equals("installEvent")
                    && m.desc.equals("(Ljava/lang/Class;)Ljava/lang/Object;")) {
                callsInstall = true;
            }
            if (insn instanceof TypeInsnNode t && t.getOpcode() == Opcodes.CHECKCAST
                    && t.desc.equals("net/fabricmc/fabric/api/event/Event")) {
                castsEvent = true;
            }
            if (insn instanceof FieldInsnNode f && f.getOpcode() == Opcodes.PUTSTATIC
                    && f.name.equals("EVENT")) {
                putsEvent = true;
            }
        }
        assertTrue(callsInstall, "<clinit> must call CommandRegistrationV1Bridge.installEvent(Class)");
        assertTrue(castsEvent, "<clinit> must checkcast the result to Event before putstatic");
        assertTrue(putsEvent, "<clinit> must store the result into EVENT");
    }

    @Test
    @DisplayName("shim redirects the removed v1 class onto the synthetic")
    void shimRegistersClassRedirect() {
        RetromodTransformer t = RetromodTransformer.getInstance();
        new FabricCommandV1Shim().registerRedirects(t);
        assertEquals(SYNTH, t.getClassRedirects().get(OLD_V1),
                "command/v1/CommandRegistrationCallback must redirect to the synthetic v1 interface");
    }
}
