/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux. Licensed under MIT License.
 */
package com.retromod.gui;

import com.retromod.util.McI18n;
import com.retromod.util.McReflect;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * In-game config editor for Retromod.
 *
 * <p>Renders a clean grid of toggle rows (label + ON/OFF button) and a Done
 * button, all inside a Screen subclass generated by {@link ScreenClassGenerator}.
 * Widget creation and mutation happen on MC's render thread (inside init()),
 * so there is no concurrent-modification hazard.
 *
 * <p>All Minecraft API access is reflective so the module compiles without an
 * MC dependency on the classpath.
 */
public final class ConfigScreenFactory {

    private static final Logger LOGGER = LoggerFactory.getLogger("Retromod");
    private static final Path CONFIG_PATH = Path.of("config/retromod/config.json");

    // Cached MC classes
    private static Class<?> screenClass;
    private static Class<?> textClass;
    private static Class<?> buttonWidgetClass;
    private static Class<?> minecraftClientClass;
    private static Class<?> pressActionClass;
    private static boolean resolved;

    /**
     * Boolean config keys in display order. The visible label for each row
     * comes from the translation key {@code retromod.settings.<key>}, so
     * these are just the config.json keys; labels live in lang files.
     */
    private static final String[] TOGGLE_KEYS = {
        "use_aot",
        "use_hybrid",
        "transform_mixins",
        "transform_refmaps",
        "remap_reflection",
        "polyfills_enabled",
        "verify_transforms",
        "force_translate_complex",
        "log_transformations",
        "debug",
    };

    private ConfigScreenFactory() {}

    // PUBLIC API

    /**
     * Open the config editor in-game. Returns to {@code parentScreen} on close.
     */
    public static void open(Object parentScreen) {
        if (!resolveClasses()) {
            LOGGER.warn("Cannot open config screen - MC classes not available");
            return;
        }

        final Map<String, Boolean> config = loadConfig();

        Object title = McI18n.translatable("retromod.settings.title");
        if (title == null) return;

        // Build the screen; widgets are added from init() on the render thread.
        Object screen = ScreenClassGenerator.createScreen(
                title,
                /* initCallback  */ s -> addAllWidgets(s, config, parentScreen),
                /* closeCallback */ () -> saveConfig(config)
        );

        if (screen != null) {
            setScreen(screen);
        }
    }

    // WIDGET LAYOUT

    /**
     * Called from the generated screen's init(). Adds one toggle row per
     * config option plus a Done button at the bottom.
     */
    private static void addAllWidgets(Object screen,
                                       Map<String, Boolean> config,
                                       Object parentScreen) {
        try {
            int width  = McReflect.getIntField(screen, screenClass, 854, "width");
            int height = McReflect.getIntField(screen, screenClass, 480, "height");

            // The bottom area is reserved for the Done button so toggle rows
            // can never overlap it. Available content height = whatever's
            // left between the top margin and the Done band. If the toggles
            // don't fit, we tighten the row spacing so they always do.
            int topMargin    = 30;   // below title
            int bottomMargin = 8;    // gap above screen edge
            int doneHeight   = 20;
            int doneGap      = 8;    // gap between content and Done button
            int statusHeight = 16;   // authenticity status line above Done
            int statusGap    = 4;

            int doneY = height - bottomMargin - doneHeight;
            int statusY = doneY - statusGap - statusHeight;
            int contentTop = topMargin;
            int contentBottom = statusY - doneGap; // status band is reserved like Done
            int contentH = Math.max(50, contentBottom - contentTop);

            int rowWidth   = 300;
            int labelWidth = 200;
            int toggleWidth = rowWidth - labelWidth - 4;
            int startX = width / 2 - rowWidth / 2;

            // Tighten row height/spacing so all toggles fit in contentH
            // without requiring a scroll bar.
            int totalRows = TOGGLE_KEYS.length;
            int desiredRowH = 20;
            int desiredSpacing = 4;
            int rowH;
            int rowSpacing;
            int desiredTotal = totalRows * (desiredRowH + desiredSpacing);
            if (desiredTotal <= contentH) {
                rowH = desiredRowH;
                rowSpacing = desiredSpacing;
            } else {
                // Squeeze: shrink height first, then spacing
                int unitsAvail = contentH / totalRows;
                rowH = Math.max(12, Math.min(desiredRowH, unitsAvail - 2));
                rowSpacing = Math.max(1, unitsAvail - rowH);
            }

            // (No action row: Add Mods / Open Mods Folder live in the
            // main Retromod screen; this is the settings-only screen.)

            for (int i = 0; i < totalRows; i++) {
                final String key = TOGGLE_KEYS[i];
                int rowY = contentTop + i * (rowH + rowSpacing);

                Object labelText = McI18n.translatable("retromod.settings." + key);
                Object labelBtn = buildButton(labelText,
                        makePressAction(() -> toggleAndRebuild(screen, config, parentScreen, key)),
                        startX, rowY, labelWidth, rowH);
                addWidget(screen, labelBtn);

                boolean value = config.getOrDefault(key, false);
                Object toggleText = McI18n.translatable(
                        value ? "retromod.settings.on" : "retromod.settings.off");
                Object toggleBtn = buildButton(toggleText,
                        makePressAction(() -> toggleAndRebuild(screen, config, parentScreen, key)),
                        startX + labelWidth + 4, rowY, toggleWidth, rowH);
                addWidget(screen, toggleBtn);
            }

            // displayLine() is §-colored ("§aVerified build§r", …) and verify()
            // is cached after the startup verifyAndLog(), so no I/O happens on
            // the render thread. Informational only; pressing does nothing.
            Object statusText = McI18n.literal(
                    com.retromod.security.SignatureVerifier.verify().displayLine());
            if (statusText != null) {
                Object statusRow = buildButton(statusText,
                        makePressAction(() -> { }),
                        width / 2 - rowWidth / 2, statusY, rowWidth, statusHeight);
                addWidget(screen, statusRow);
            }

            Object doneBtn = buildButton(McI18n.translatable("retromod.settings.done"),
                    makePressAction(() -> setScreen(parentScreen)),
                    width / 2 - 75, doneY, 150, doneHeight);
            addWidget(screen, doneBtn);

        } catch (Exception e) {
            LOGGER.warn("Could not add config widgets: {}", e.getMessage());
        }
    }

    /**
     * Toggle a value, save, and rebuild the screen (simplest way to update
     * button labels since MC button messages vary across versions).
     */
    private static void toggleAndRebuild(Object screen,
                                          Map<String, Boolean> config,
                                          Object parentScreen,
                                          String key) {
        boolean newVal = !config.getOrDefault(key, false);
        config.put(key, newVal);
        saveConfig(config);

        // Re-open the screen to refresh button labels; runs on render thread
        // because the press action is dispatched by MC on the render thread.
        Object title = McI18n.translatable("retromod.settings.title");
        Object fresh = ScreenClassGenerator.createScreen(
                title,
                s -> addAllWidgets(s, config, parentScreen),
                () -> saveConfig(config)
        );
        if (fresh != null) setScreen(fresh);
    }

    // BUTTON BUILDERS

    /**
     * Build a button whose label is a pre-constructed Text/Component.
     * Callers pass a translatable Text from {@link McI18n} so the label
     * localizes correctly at render time.
     */
    private static Object buildButton(Object text, Object pressAction,
                                       int x, int y, int w, int h) {
        try {
            if (text == null || pressAction == null) return null;

            Method builderMethod = McReflect.findMethod(buttonWidgetClass,
                    new Class[]{textClass, pressActionClass}, "builder");
            if (builderMethod == null) return null;

            Object builder = builderMethod.invoke(null, text, pressAction);

            Method dim = McReflect.findMethod(builder.getClass(),
                    new Class[]{int.class, int.class, int.class, int.class},
                    "dimensions", "bounds", "pos");
            if (dim != null) builder = dim.invoke(builder, x, y, w, h);

            Method buildMethod = McReflect.findMethod(builder.getClass(), "build");
            if (buildMethod == null) return null;
            return buildMethod.invoke(builder);
        } catch (Exception e) {
            LOGGER.debug("Could not build button: {}", e.getMessage());
            return null;
        }
    }

    private static Object makePressAction(Runnable onPress) {
        if (pressActionClass == null) return null;
        return Proxy.newProxyInstance(
                pressActionClass.getClassLoader(),
                new Class<?>[]{pressActionClass},
                (proxy, method, args) -> {
                    if (method.getDeclaringClass() != Object.class) {
                        onPress.run();
                    }
                    return null;
                });
    }

    private static void addWidget(Object screen, Object widget) {
        if (widget == null) return;
        try {
            Method add = McReflect.findMethod(screenClass,
                    "addDrawableChild", "addRenderableWidget", "addWidget");
            if (add != null) {
                add.setAccessible(true);
                add.invoke(screen, widget);
            }
        } catch (Exception e) {
            LOGGER.debug("Could not add widget: {}", e.getMessage());
        }
    }

    // CONFIG I/O

    static Map<String, Boolean> loadConfig() {
        Map<String, Boolean> config = new LinkedHashMap<>();
        config.put("use_aot", true);
        config.put("use_hybrid", true);
        config.put("instruction_level_granularity", true);
        config.put("transform_mixins", true);
        config.put("transform_refmaps", true);
        config.put("remap_reflection", true);
        config.put("log_transformations", false);
        config.put("debug", false);
        config.put("dump_bytecode", false);
        config.put("force_translate_complex", false);
        config.put("polyfills_enabled", true);
        config.put("verify_transforms", true);

        try {
            if (Files.exists(CONFIG_PATH)) {
                String json = Files.readString(CONFIG_PATH);
                for (String key : config.keySet()) {
                    if (json.contains("\"" + key + "\": true") ||
                        json.contains("\"" + key + "\":true")) {
                        config.put(key, true);
                    } else if (json.contains("\"" + key + "\": false") ||
                               json.contains("\"" + key + "\":false")) {
                        config.put(key, false);
                    }
                }
            }
        } catch (Exception e) {
            LOGGER.debug("Could not load config: {}", e.getMessage());
        }
        return config;
    }

    static void saveConfig(Map<String, Boolean> config) {
        try {
            Files.createDirectories(CONFIG_PATH.getParent());

            String existing = Files.exists(CONFIG_PATH) ? Files.readString(CONFIG_PATH) : "";
            String targetVersion = extractStringValue(existing, "target_mc_version", "auto");
            String logLevel = extractStringValue(existing, "log_level", "INFO");

            StringBuilder sb = new StringBuilder();
            sb.append("{\n");
            sb.append("  \"_comment\": \"Retromod Configuration - https://github.com/Bownlux/Retromod\",\n\n");
            sb.append("  \"use_aot\": ").append(config.getOrDefault("use_aot", true)).append(",\n");
            sb.append("  \"use_hybrid\": ").append(config.getOrDefault("use_hybrid", true)).append(",\n");
            sb.append("  \"instruction_level_granularity\": ").append(config.getOrDefault("instruction_level_granularity", true)).append(",\n\n");
            sb.append("  \"transform_mixins\": ").append(config.getOrDefault("transform_mixins", true)).append(",\n");
            sb.append("  \"transform_refmaps\": ").append(config.getOrDefault("transform_refmaps", true)).append(",\n\n");
            sb.append("  \"remap_reflection\": ").append(config.getOrDefault("remap_reflection", true)).append(",\n\n");
            sb.append("  \"log_level\": \"").append(logLevel).append("\",\n");
            sb.append("  \"log_transformations\": ").append(config.getOrDefault("log_transformations", false)).append(",\n\n");
            sb.append("  \"target_mc_version\": \"").append(targetVersion).append("\",\n\n");
            sb.append("  \"debug\": ").append(config.getOrDefault("debug", false)).append(",\n");
            sb.append("  \"dump_bytecode\": ").append(config.getOrDefault("dump_bytecode", false)).append(",\n\n");
            sb.append("  \"force_translate_complex\": ").append(config.getOrDefault("force_translate_complex", false)).append(",\n\n");
            sb.append("  \"polyfills_enabled\": ").append(config.getOrDefault("polyfills_enabled", true)).append(",\n\n");
            sb.append("  \"verify_transforms\": ").append(config.getOrDefault("verify_transforms", true)).append("\n");
            sb.append("}\n");

            Files.writeString(CONFIG_PATH, sb.toString());
        } catch (Exception e) {
            LOGGER.warn("Could not save config: {}", e.getMessage());
        }
    }

    private static String extractStringValue(String json, String key, String defaultValue) {
        if (json == null || json.isEmpty()) return defaultValue;
        int idx = json.indexOf("\"" + key + "\"");
        if (idx < 0) return defaultValue;
        int colon = json.indexOf(':', idx);
        if (colon < 0) return defaultValue;
        int qStart = json.indexOf('"', colon + 1);
        if (qStart < 0) return defaultValue;
        int qEnd = json.indexOf('"', qStart + 1);
        if (qEnd < 0) return defaultValue;
        return json.substring(qStart + 1, qEnd);
    }

    // MC CLASS RESOLUTION

    private static boolean resolveClasses() {
        if (resolved) return screenClass != null;
        resolved = true;

        screenClass = McReflect.findClass(
            "net.minecraft.client.gui.screen.Screen",
            "net.minecraft.client.gui.screens.Screen"
        );
        textClass = McReflect.findClass(
            "net.minecraft.text.Text",
            "net.minecraft.network.chat.Component"
        );
        buttonWidgetClass = McReflect.findClass(
            "net.minecraft.client.gui.widget.ButtonWidget",
            "net.minecraft.client.gui.components.Button"
        );
        minecraftClientClass = McReflect.findClass(
            "net.minecraft.client.MinecraftClient",
            "net.minecraft.client.Minecraft"
        );

        if (buttonWidgetClass != null) {
            // yarn: ButtonWidget$PressAction, mojang: Button$OnPress
            for (Class<?> inner : buttonWidgetClass.getDeclaredClasses()) {
                if (inner.isInterface() && inner.getMethods().length <= 2) {
                    pressActionClass = inner;
                    break;
                }
            }
        }
        if (pressActionClass == null) {
            pressActionClass = McReflect.findClass(
                "net.minecraft.client.gui.widget.ButtonWidget$PressAction",
                "net.minecraft.client.gui.components.Button$OnPress"
            );
        }

        return screenClass != null && textClass != null && buttonWidgetClass != null;
    }

    private static void setScreen(Object screen) {
        try {
            Object client = getClientInstance();
            if (client == null) return;
            Method set = McReflect.findMethod(minecraftClientClass,
                    new Class[]{screenClass}, "setScreen");
            if (set != null) set.invoke(client, screen);
        } catch (Exception e) {
            LOGGER.debug("Could not set screen: {}", e.getMessage());
        }
    }

    private static Object getClientInstance() {
        try {
            Method getInstance = McReflect.findMethod(minecraftClientClass, "getInstance");
            if (getInstance != null) return getInstance.invoke(null);
        } catch (Exception e) {
            LOGGER.debug("Could not get MC client: {}", e.getMessage());
        }
        return null;
    }
}
