/*
 * Retromod - Backwards Compatibility Layer for Minecraft Mods
 * Copyright (c) 2026 Bownlux. Licensed under MIT License.
 */
package com.retromod.shim.common;

import com.retromod.core.RetromodTransformer;

/**
 * 26.1 to 26.2 core class moves and renames, shared by the Fabric, NeoForge, and Forge
 * shims (Mojang names on every loader, so the table is loader-independent; each loader
 * wraps it in its own shim since ShimRegistry's BFS runs per-loader).
 *
 * <p>Generated by {@code scripts/harvest-mc-diff.py} from the 26.1.2 and 26.2-rc-1 client
 * jars, then hand-verified. Mostly 26.2 splitting {@code advancements/criterion/*} into
 * {@code triggers/*} and {@code predicates/*}; plus Slime/MagmaCube moving under
 * {@code monster/cubemob/AbstractCubeMob}, {@code contextualbar} renderers dropping the
 * {@code Renderer} suffix, and {@code SubmitNodeStorage}'s {@code *Submit} records moving
 * into {@code renderer/feature/*FeatureRenderer$Submit}.
 *
 * <p>{@code client/gui/Gui} is intentionally absent: 26.2 split off a new {@code Hud}
 * class but {@code Gui} still exists, so redirecting it would hijack a live class. Removals
 * with no successor ({@code MultiBufferSource}, {@code Tesselator}, {@code VertexFormat$Mode},
 * {@code util/Tuple}, {@code ShareToLanScreen}) need bridges instead.
 */
public final class Mc26_1To26_2CoreMoves {

    private Mc26_1To26_2CoreMoves() {}

    public static void register(RetromodTransformer t) {
        // 26.2 changed the STRUCTURE_PROCESSOR registry to hold MapCodecs directly; a 1.21.x
        // mod's SAM-lambda registration then breaks every datapack processor_list that
        // references it. Convert at the Registry.register boundary (#98 worldgen chain).
        WorldgenTypeBridgeSynthetic.register(t);

        // 26.2 deleted MultiBufferSource/BufferSource/Tesselator and replaced VertexFormat$Mode
        // with PrimitiveTopology; any mod class referencing them dies NoClassDefFoundError at
        // class load on 26.2 even if the render path never runs. Stand-ins keep them loading
        // (and their buffer-building code working); frame submission is staged.
        RenderBufferSynthetics.register(t);

        // StructureProcessor itself became an INTERFACE on 26.2 (26.1: abstract class), so a
        // 1.21.x processor's `extends StructureProcessor` dies at class definition with
        // IncompatibleClassChangeError "has interface ... as super class" (YUNG's Better
        // Dungeons processors on the 26.2 server). Rebase to Object + implement the interface.
        t.registerSuperclassRebase(
            "net/minecraft/world/level/levelgen/structure/templatesystem/StructureProcessor",
            "java/lang/Object",
            "net/minecraft/world/level/levelgen/structure/templatesystem/StructureProcessor");

        t.registerClassRedirect("com/mojang/blaze3d/pipeline/RenderPipeline$UniformDescription",
                "com/mojang/blaze3d/pipeline/BindGroupLayout$UniformDescription");

        t.registerClassRedirect("net/minecraft/advancements/CriteriaTriggers",
                "net/minecraft/advancements/triggers/CriteriaTriggers");
        t.registerClassRedirect("net/minecraft/advancements/Criterion",
                "net/minecraft/advancements/triggers/Criterion");
        t.registerClassRedirect("net/minecraft/advancements/CriterionTrigger",
                "net/minecraft/advancements/triggers/CriterionTrigger");

        t.registerClassRedirect("net/minecraft/advancements/criterion/AnyBlockInteractionTrigger",
                "net/minecraft/advancements/triggers/AnyBlockInteractionTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/AnyBlockInteractionTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/AnyBlockInteractionTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/BeeNestDestroyedTrigger",
                "net/minecraft/advancements/triggers/BeeNestDestroyedTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/BeeNestDestroyedTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/BeeNestDestroyedTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/BlockPredicate",
                "net/minecraft/advancements/predicates/BlockPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/BlockPredicate$Builder",
                "net/minecraft/advancements/predicates/BlockPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/BredAnimalsTrigger",
                "net/minecraft/advancements/triggers/BredAnimalsTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/BredAnimalsTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/BredAnimalsTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/BrewedPotionTrigger",
                "net/minecraft/advancements/triggers/BrewedPotionTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/BrewedPotionTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/BrewedPotionTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ChangeDimensionTrigger",
                "net/minecraft/advancements/triggers/ChangeDimensionTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ChangeDimensionTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/ChangeDimensionTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ChanneledLightningTrigger",
                "net/minecraft/advancements/triggers/ChanneledLightningTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ChanneledLightningTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/ChanneledLightningTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionContentsPredicate",
                "net/minecraft/advancements/predicates/CollectionContentsPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionContentsPredicate$Multiple",
                "net/minecraft/advancements/predicates/CollectionContentsPredicate$Multiple");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionContentsPredicate$Single",
                "net/minecraft/advancements/predicates/CollectionContentsPredicate$Single");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionContentsPredicate$Zero",
                "net/minecraft/advancements/predicates/CollectionContentsPredicate$Zero");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionCountsPredicate",
                "net/minecraft/advancements/predicates/CollectionCountsPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionCountsPredicate$Entry",
                "net/minecraft/advancements/predicates/CollectionCountsPredicate$Entry");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionCountsPredicate$Multiple",
                "net/minecraft/advancements/predicates/CollectionCountsPredicate$Multiple");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionCountsPredicate$Single",
                "net/minecraft/advancements/predicates/CollectionCountsPredicate$Single");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionCountsPredicate$Zero",
                "net/minecraft/advancements/predicates/CollectionCountsPredicate$Zero");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CollectionPredicate",
                "net/minecraft/advancements/predicates/CollectionPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ConstructBeaconTrigger",
                "net/minecraft/advancements/triggers/ConstructBeaconTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ConstructBeaconTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/ConstructBeaconTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ConsumeItemTrigger",
                "net/minecraft/advancements/triggers/ConsumeItemTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ConsumeItemTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/ConsumeItemTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ContextAwarePredicate",
                "net/minecraft/advancements/predicates/ContextAwarePredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CuredZombieVillagerTrigger",
                "net/minecraft/advancements/triggers/CuredZombieVillagerTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/CuredZombieVillagerTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/CuredZombieVillagerTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DamagePredicate",
                "net/minecraft/advancements/predicates/DamagePredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DamagePredicate$Builder",
                "net/minecraft/advancements/predicates/DamagePredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DamageSourcePredicate",
                "net/minecraft/advancements/predicates/DamageSourcePredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DamageSourcePredicate$Builder",
                "net/minecraft/advancements/predicates/DamageSourcePredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DataComponentMatchers",
                "net/minecraft/advancements/predicates/DataComponentMatchers");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DataComponentMatchers$Builder",
                "net/minecraft/advancements/predicates/DataComponentMatchers$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DefaultBlockInteractionTrigger",
                "net/minecraft/advancements/triggers/DefaultBlockInteractionTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DefaultBlockInteractionTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/DefaultBlockInteractionTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DistancePredicate",
                "net/minecraft/advancements/predicates/DistancePredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DistanceTrigger",
                "net/minecraft/advancements/triggers/DistanceTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/DistanceTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/DistanceTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EffectsChangedTrigger",
                "net/minecraft/advancements/triggers/EffectsChangedTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EffectsChangedTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/EffectsChangedTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EnchantedItemTrigger",
                "net/minecraft/advancements/triggers/EnchantedItemTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EnchantedItemTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/EnchantedItemTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EnchantmentPredicate",
                "net/minecraft/advancements/predicates/EnchantmentPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EnterBlockTrigger",
                "net/minecraft/advancements/triggers/EnterBlockTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EnterBlockTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/EnterBlockTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityEquipmentPredicate",
                "net/minecraft/advancements/predicates/entity/EntityEquipmentPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityEquipmentPredicate$Builder",
                "net/minecraft/advancements/predicates/entity/EntityEquipmentPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityFlagsPredicate",
                "net/minecraft/advancements/predicates/entity/EntityFlagsPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityFlagsPredicate$Builder",
                "net/minecraft/advancements/predicates/entity/EntityFlagsPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityHurtPlayerTrigger",
                "net/minecraft/advancements/triggers/EntityHurtPlayerTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityHurtPlayerTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/EntityHurtPlayerTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityPredicate",
                "net/minecraft/advancements/predicates/entity/EntityPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityPredicate$Builder",
                "net/minecraft/advancements/predicates/entity/EntityPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntitySubPredicate",
                "net/minecraft/advancements/predicates/entity/EntitySubPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntitySubPredicates",
                "net/minecraft/advancements/predicates/entity/EntitySubPredicates");
        t.registerClassRedirect("net/minecraft/advancements/criterion/EntityTypePredicate",
                "net/minecraft/advancements/predicates/entity/EntityTypePredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FallAfterExplosionTrigger",
                "net/minecraft/advancements/triggers/FallAfterExplosionTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FallAfterExplosionTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/FallAfterExplosionTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FilledBucketTrigger",
                "net/minecraft/advancements/triggers/FilledBucketTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FilledBucketTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/FilledBucketTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FishingHookPredicate",
                "net/minecraft/advancements/predicates/entity/FishingHookPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FishingRodHookedTrigger",
                "net/minecraft/advancements/triggers/FishingRodHookedTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FishingRodHookedTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/FishingRodHookedTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FluidPredicate",
                "net/minecraft/advancements/predicates/FluidPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FluidPredicate$Builder",
                "net/minecraft/advancements/predicates/FluidPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FoodPredicate",
                "net/minecraft/advancements/predicates/FoodPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/FoodPredicate$Builder",
                "net/minecraft/advancements/predicates/FoodPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/GameTypePredicate",
                "net/minecraft/advancements/predicates/GameTypePredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ImpossibleTrigger",
                "net/minecraft/advancements/triggers/ImpossibleTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ImpossibleTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/ImpossibleTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/InputPredicate",
                "net/minecraft/advancements/predicates/InputPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/InventoryChangeTrigger",
                "net/minecraft/advancements/triggers/InventoryChangeTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/InventoryChangeTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/InventoryChangeTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/InventoryChangeTrigger$TriggerInstance$Slots",
                "net/minecraft/advancements/triggers/InventoryChangeTrigger$TriggerInstance$Slots");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ItemDurabilityTrigger",
                "net/minecraft/advancements/triggers/ItemDurabilityTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ItemDurabilityTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/ItemDurabilityTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ItemPredicate",
                "net/minecraft/advancements/predicates/ItemPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ItemPredicate$Builder",
                "net/minecraft/advancements/predicates/ItemPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ItemUsedOnLocationTrigger",
                "net/minecraft/advancements/triggers/ItemUsedOnLocationTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ItemUsedOnLocationTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/ItemUsedOnLocationTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/KilledByArrowTrigger",
                "net/minecraft/advancements/triggers/KilledByArrowTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/KilledByArrowTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/KilledByArrowTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/KilledTrigger",
                "net/minecraft/advancements/triggers/KilledTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/KilledTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/KilledTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LevitationTrigger",
                "net/minecraft/advancements/triggers/LevitationTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LevitationTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/LevitationTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LightPredicate",
                "net/minecraft/advancements/predicates/LightPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LightPredicate$Builder",
                "net/minecraft/advancements/predicates/LightPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LightningBoltPredicate",
                "net/minecraft/advancements/predicates/entity/LightningBoltPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LightningStrikeTrigger",
                "net/minecraft/advancements/triggers/LightningStrikeTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LightningStrikeTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/LightningStrikeTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LocationPredicate",
                "net/minecraft/advancements/predicates/LocationPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LocationPredicate$Builder",
                "net/minecraft/advancements/predicates/LocationPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LocationPredicate$PositionPredicate",
                "net/minecraft/advancements/predicates/LocationPredicate$PositionPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LootTableTrigger",
                "net/minecraft/advancements/triggers/LootTableTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/LootTableTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/LootTableTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MinMaxBounds",
                "net/minecraft/advancements/predicates/MinMaxBounds");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MinMaxBounds$Bounds",
                "net/minecraft/advancements/predicates/MinMaxBounds$Bounds");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MinMaxBounds$Doubles",
                "net/minecraft/advancements/predicates/MinMaxBounds$Doubles");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MinMaxBounds$FloatDegrees",
                "net/minecraft/advancements/predicates/MinMaxBounds$FloatDegrees");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MinMaxBounds$Ints",
                "net/minecraft/advancements/predicates/MinMaxBounds$Ints");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MobEffectsPredicate",
                "net/minecraft/advancements/predicates/MobEffectsPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MobEffectsPredicate$Builder",
                "net/minecraft/advancements/predicates/MobEffectsPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MobEffectsPredicate$MobEffectInstancePredicate",
                "net/minecraft/advancements/predicates/MobEffectsPredicate$MobEffectInstancePredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/MovementPredicate",
                "net/minecraft/advancements/predicates/entity/MovementPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/NbtPredicate",
                "net/minecraft/advancements/predicates/NbtPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PickedUpItemTrigger",
                "net/minecraft/advancements/triggers/PickedUpItemTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PickedUpItemTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/PickedUpItemTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerHurtEntityTrigger",
                "net/minecraft/advancements/triggers/PlayerHurtEntityTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerHurtEntityTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/PlayerHurtEntityTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerInteractTrigger",
                "net/minecraft/advancements/triggers/PlayerInteractTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerInteractTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/PlayerInteractTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerPredicate",
                "net/minecraft/advancements/predicates/entity/PlayerPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerPredicate$AdvancementCriterionsPredicate",
                "net/minecraft/advancements/predicates/entity/PlayerPredicate$AdvancementCriterionsPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerPredicate$AdvancementDonePredicate",
                "net/minecraft/advancements/predicates/entity/PlayerPredicate$AdvancementDonePredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerPredicate$AdvancementPredicate",
                "net/minecraft/advancements/predicates/entity/PlayerPredicate$AdvancementPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerPredicate$Builder",
                "net/minecraft/advancements/predicates/entity/PlayerPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerPredicate$StatMatcher",
                "net/minecraft/advancements/predicates/entity/PlayerPredicate$StatMatcher");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerTrigger",
                "net/minecraft/advancements/triggers/PlayerTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/PlayerTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/PlayerTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/RaiderPredicate",
                "net/minecraft/advancements/predicates/entity/RaiderPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/RecipeCraftedTrigger",
                "net/minecraft/advancements/triggers/RecipeCraftedTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/RecipeCraftedTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/RecipeCraftedTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/RecipeUnlockedTrigger",
                "net/minecraft/advancements/triggers/RecipeUnlockedTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/RecipeUnlockedTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/RecipeUnlockedTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SheepPredicate",
                "net/minecraft/advancements/predicates/entity/SheepPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ShotCrossbowTrigger",
                "net/minecraft/advancements/triggers/ShotCrossbowTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/ShotCrossbowTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/ShotCrossbowTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SimpleCriterionTrigger",
                "net/minecraft/advancements/triggers/SimpleCriterionTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SimpleCriterionTrigger$SimpleInstance",
                "net/minecraft/advancements/triggers/SimpleCriterionTrigger$SimpleInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SingleComponentItemPredicate",
                "net/minecraft/advancements/predicates/SingleComponentItemPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SlideDownBlockTrigger",
                "net/minecraft/advancements/triggers/SlideDownBlockTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SlideDownBlockTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/SlideDownBlockTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SlimePredicate",
                "net/minecraft/advancements/predicates/entity/CubeMobPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SlotsPredicate",
                "net/minecraft/advancements/predicates/SlotsPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SpearMobsTrigger",
                "net/minecraft/advancements/triggers/SpearMobsTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SpearMobsTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/SpearMobsTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/StartRidingTrigger",
                "net/minecraft/advancements/triggers/StartRidingTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/StartRidingTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/StartRidingTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/StatePropertiesPredicate",
                "net/minecraft/advancements/predicates/StatePropertiesPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/StatePropertiesPredicate$Builder",
                "net/minecraft/advancements/predicates/StatePropertiesPredicate$Builder");
        t.registerClassRedirect("net/minecraft/advancements/criterion/StatePropertiesPredicate$ExactMatcher",
                "net/minecraft/advancements/predicates/StatePropertiesPredicate$ExactMatcher");
        t.registerClassRedirect("net/minecraft/advancements/criterion/StatePropertiesPredicate$PropertyMatcher",
                "net/minecraft/advancements/predicates/StatePropertiesPredicate$PropertyMatcher");
        t.registerClassRedirect("net/minecraft/advancements/criterion/StatePropertiesPredicate$RangedMatcher",
                "net/minecraft/advancements/predicates/StatePropertiesPredicate$RangedMatcher");
        t.registerClassRedirect("net/minecraft/advancements/criterion/StatePropertiesPredicate$ValueMatcher",
                "net/minecraft/advancements/predicates/StatePropertiesPredicate$ValueMatcher");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SummonedEntityTrigger",
                "net/minecraft/advancements/triggers/SummonedEntityTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/SummonedEntityTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/SummonedEntityTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/TagPredicate",
                "net/minecraft/advancements/predicates/TagPredicate");
        t.registerClassRedirect("net/minecraft/advancements/criterion/TameAnimalTrigger",
                "net/minecraft/advancements/triggers/TameAnimalTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/TameAnimalTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/TameAnimalTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/TargetBlockTrigger",
                "net/minecraft/advancements/triggers/TargetBlockTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/TargetBlockTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/TargetBlockTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/TradeTrigger",
                "net/minecraft/advancements/triggers/TradeTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/TradeTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/TradeTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/UsedEnderEyeTrigger",
                "net/minecraft/advancements/triggers/UsedEnderEyeTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/UsedEnderEyeTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/UsedEnderEyeTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/UsedTotemTrigger",
                "net/minecraft/advancements/triggers/UsedTotemTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/UsedTotemTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/UsedTotemTrigger$TriggerInstance");
        t.registerClassRedirect("net/minecraft/advancements/criterion/UsingItemTrigger",
                "net/minecraft/advancements/triggers/UsingItemTrigger");
        t.registerClassRedirect("net/minecraft/advancements/criterion/UsingItemTrigger$TriggerInstance",
                "net/minecraft/advancements/triggers/UsingItemTrigger$TriggerInstance");

        t.registerClassRedirect("net/minecraft/client/Minecraft$GameLoadCookie",
                "net/minecraft/client/GameLoadCookie");

        t.registerClassRedirect("net/minecraft/client/gui/contextualbar/ContextualBarRenderer",
                "net/minecraft/client/gui/contextualbar/ContextualBar");
        t.registerClassRedirect("net/minecraft/client/gui/contextualbar/ExperienceBarRenderer",
                "net/minecraft/client/gui/contextualbar/ExperienceBar");
        t.registerClassRedirect("net/minecraft/client/gui/contextualbar/JumpableVehicleBarRenderer",
                "net/minecraft/client/gui/contextualbar/JumpableVehicleBar");
        t.registerClassRedirect("net/minecraft/client/gui/contextualbar/LocatorBarRenderer",
                "net/minecraft/client/gui/contextualbar/LocatorBar");

        t.registerClassRedirect("net/minecraft/client/renderer/LevelRenderer$BrightnessGetter",
                "net/minecraft/util/LightCoordsUtil$BrightnessGetter");
        t.registerClassRedirect("net/minecraft/client/renderer/SubmitNodeStorage$FlameSubmit",
                "net/minecraft/client/renderer/feature/FlameFeatureRenderer$Submit");
        t.registerClassRedirect("net/minecraft/client/renderer/SubmitNodeStorage$ItemSubmit",
                "net/minecraft/client/renderer/feature/ItemFeatureRenderer$Submit");
        t.registerClassRedirect("net/minecraft/client/renderer/SubmitNodeStorage$LeashSubmit",
                "net/minecraft/client/renderer/feature/LeashFeatureRenderer$Submit");
        t.registerClassRedirect("net/minecraft/client/renderer/SubmitNodeStorage$ShadowSubmit",
                "net/minecraft/client/renderer/feature/ShadowFeatureRenderer$Submit");
        t.registerClassRedirect("net/minecraft/client/renderer/SubmitNodeStorage$TextSubmit",
                "net/minecraft/client/renderer/feature/TextFeatureRenderer$Submit");

        t.registerClassRedirect("net/minecraft/client/renderer/feature/BlockFeatureRenderer",
                "net/minecraft/client/renderer/feature/MovingBlockFeatureRenderer");

        t.registerClassRedirect("net/minecraft/world/entity/animal/Bucketable",
                "net/minecraft/world/entity/Bucketable");
        t.registerClassRedirect("net/minecraft/world/entity/monster/MagmaCube",
                "net/minecraft/world/entity/monster/cubemob/MagmaCube");
        t.registerClassRedirect("net/minecraft/world/entity/monster/Slime",
                "net/minecraft/world/entity/monster/cubemob/Slime");
        t.registerClassRedirect("net/minecraft/world/entity/monster/Slime$SlimeAttackGoal",
                "net/minecraft/world/entity/monster/cubemob/AbstractCubeMob$CubeMobAttackGoal");
        t.registerClassRedirect("net/minecraft/world/entity/monster/Slime$SlimeFloatGoal",
                "net/minecraft/world/entity/monster/cubemob/AbstractCubeMob$CubeMobFloatGoal");
        t.registerClassRedirect("net/minecraft/world/entity/monster/Slime$SlimeKeepOnJumpingGoal",
                "net/minecraft/world/entity/monster/cubemob/AbstractCubeMob$CubeMobKeepOnJumpingGoal");
        t.registerClassRedirect("net/minecraft/world/entity/monster/Slime$SlimeMoveControl",
                "net/minecraft/world/entity/monster/cubemob/AbstractCubeMob$CubeMobMoveControl");
        t.registerClassRedirect("net/minecraft/world/entity/monster/Slime$SlimeRandomDirectionGoal",
                "net/minecraft/world/entity/monster/cubemob/AbstractCubeMob$CubeMobRandomDirectionGoal");

        // 26.2 moved the registry constants from EntityType/BlockEntityType into new
        // EntityTypes/BlockEntityTypes holders (same field names and descriptors, new owner).
        for (String f : ENTITY_TYPE_CONSTANTS) {
            t.registerFieldRedirect("net/minecraft/world/entity/EntityType", f,
                    "net/minecraft/world/entity/EntityTypes", f);
        }
        for (String f : BLOCK_ENTITY_TYPE_CONSTANTS) {
            t.registerFieldRedirect("net/minecraft/world/level/block/entity/BlockEntityType", f,
                    "net/minecraft/world/level/block/entity/BlockEntityTypes", f);
        }

        // 26.2 folded each per-color family (16 colors) of Block/Item constants into a single
        // ColorCollection field and dropped the per-color constants (Blocks.WHITE_WOOL -> Blocks.WOOL,
        // Blocks.WHITE_CANDLE -> Blocks.DYED_CANDLE). Rewrite each old GETSTATIC as
        // <owner>.<collection>.pick(DyeColor.<COLOR>) cast back to Block/Item. The collection field name
        // is IRREGULAR (WOOL keeps its name; CANDLE/TERRACOTTA/SHULKER_BOX gain a DYED_ prefix), so each
        // family carries its exact collection field. Every collection field below was verified present on
        // 26.2 Blocks/Items, and every per-color constant was verified REMOVED (so an accessor never
        // shadows a live field). Shared across loaders: 26.2 is Mojang-named on Fabric/NeoForge/Forge alike.
        // Blocks (suffix -> collection field on Blocks):
        registerDyedFields(t, BLOCKS, BLOCK, "WOOL", "WOOL");
        registerDyedFields(t, BLOCKS, BLOCK, "CARPET", "CARPET");
        registerDyedFields(t, BLOCKS, BLOCK, "CONCRETE", "CONCRETE");
        registerDyedFields(t, BLOCKS, BLOCK, "CONCRETE_POWDER", "CONCRETE_POWDER");
        registerDyedFields(t, BLOCKS, BLOCK, "STAINED_GLASS", "STAINED_GLASS");
        registerDyedFields(t, BLOCKS, BLOCK, "STAINED_GLASS_PANE", "STAINED_GLASS_PANE");
        registerDyedFields(t, BLOCKS, BLOCK, "BED", "BED");
        registerDyedFields(t, BLOCKS, BLOCK, "BANNER", "BANNER");
        registerDyedFields(t, BLOCKS, BLOCK, "WALL_BANNER", "WALL_BANNER");
        registerDyedFields(t, BLOCKS, BLOCK, "GLAZED_TERRACOTTA", "GLAZED_TERRACOTTA");
        registerDyedFields(t, BLOCKS, BLOCK, "TERRACOTTA", "DYED_TERRACOTTA");
        registerDyedFields(t, BLOCKS, BLOCK, "SHULKER_BOX", "DYED_SHULKER_BOX");
        registerDyedFields(t, BLOCKS, BLOCK, "CANDLE", "DYED_CANDLE");
        registerDyedFields(t, BLOCKS, BLOCK, "CANDLE_CAKE", "DYED_CANDLE_CAKE");
        // Items (suffix -> collection field on Items). Items adds DYE and DYED_BUNDLE (no block form) and
        // omits CANDLE_CAKE / WALL_BANNER (block-only). HARNESS is new in 26.2 with no pre-26.2 per-color
        // constant, so it needs no accessor.
        registerDyedFields(t, ITEMS, ITEM, "WOOL", "WOOL");
        registerDyedFields(t, ITEMS, ITEM, "CARPET", "CARPET");
        registerDyedFields(t, ITEMS, ITEM, "CONCRETE", "CONCRETE");
        registerDyedFields(t, ITEMS, ITEM, "CONCRETE_POWDER", "CONCRETE_POWDER");
        registerDyedFields(t, ITEMS, ITEM, "STAINED_GLASS", "STAINED_GLASS");
        registerDyedFields(t, ITEMS, ITEM, "STAINED_GLASS_PANE", "STAINED_GLASS_PANE");
        registerDyedFields(t, ITEMS, ITEM, "BED", "BED");
        registerDyedFields(t, ITEMS, ITEM, "BANNER", "BANNER");
        registerDyedFields(t, ITEMS, ITEM, "GLAZED_TERRACOTTA", "GLAZED_TERRACOTTA");
        registerDyedFields(t, ITEMS, ITEM, "TERRACOTTA", "DYED_TERRACOTTA");
        registerDyedFields(t, ITEMS, ITEM, "SHULKER_BOX", "DYED_SHULKER_BOX");
        registerDyedFields(t, ITEMS, ITEM, "CANDLE", "DYED_CANDLE");
        registerDyedFields(t, ITEMS, ITEM, "DYE", "DYE");
        registerDyedFields(t, ITEMS, ITEM, "BUNDLE", "DYED_BUNDLE");

        // Minecraft.setScreen(Screen) was removed in 26.2 (setScreenAndShow, same descriptor, is the
        // surviving variant; BOTH exist on 26.1, verified against 26.1-snapshot-10 vs the 26.2 jar,
        // which is why this lives in the 26.1->26.2 shim and not 1.21.11->26.1). Extremely common
        // in mods and mixin selectors (corpus scan: dynamic-fps MinecraftMixin).
        t.registerMethodRedirect(
            "net/minecraft/client/Minecraft", "setScreen",
            "(Lnet/minecraft/client/gui/screens/Screen;)V",
            "net/minecraft/client/Minecraft", "setScreenAndShow",
            "(Lnet/minecraft/client/gui/screens/Screen;)V"
        );

        // AbstractContainerScreen.renderLabels -> extractLabels in 26.2 (renderLabels present on 26.1,
        // gone on 26.2, which now has extractLabels(GuiGraphicsExtractor,II)V; the param GuiGraphics ->
        // GuiGraphicsExtractor move is already handled). Mirrors the 26.1 render -> extractRenderState
        // pair. Corpus scan: Apollo's Enchantment AnvilScreenMixin (#137) - its @WrapOperation on this
        // method went inert, and a hard WrapOperation miss can abort sibling mixins in the same config.
        t.registerMethodRedirect(
            "net/minecraft/client/gui/screens/inventory/AbstractContainerScreen", "renderLabels",
            "(Lnet/minecraft/client/gui/GuiGraphics;II)V",
            "net/minecraft/client/gui/screens/inventory/AbstractContainerScreen", "extractLabels",
            "(Lnet/minecraft/client/gui/GuiGraphicsExtractor;II)V"
        );

        // GameRenderer.getMainCamera() -> mainCamera() in 26.2 (getMainCamera present on 26.1, gone on
        // 26.2 where mainCamera() is the accessor; same Camera return). Owner+desc-scoped. Corpus:
        // 10 of the top-40 NeoForge 1.21.1 mods (camera-reading client mods) call it.
        t.registerMethodRedirect(
            "net/minecraft/client/renderer/GameRenderer", "getMainCamera",
            "()Lnet/minecraft/client/Camera;",
            "net/minecraft/client/renderer/GameRenderer", "mainCamera",
            "()Lnet/minecraft/client/Camera;"
        );
    }

    private static final String BLOCKS = "net/minecraft/world/level/block/Blocks";
    private static final String ITEMS = "net/minecraft/world/item/Items";
    private static final String BLOCK = "net/minecraft/world/level/block/Block";
    private static final String ITEM = "net/minecraft/world/item/Item";
    private static final String COLOR_COLLECTION = "net/minecraft/world/level/block/ColorCollection";
    private static final String DYE_COLOR = "net/minecraft/world/item/DyeColor";
    private static final String[] DYE_COLORS = {
        "WHITE", "ORANGE", "MAGENTA", "LIGHT_BLUE", "YELLOW", "LIME", "PINK", "GRAY",
        "LIGHT_GRAY", "CYAN", "PURPLE", "BLUE", "BROWN", "GREEN", "RED", "BLACK"
    };

    // Maps a family's 16 per-color fields (WHITE_WOOL) to <owner>.<collection>.pick(color) cast to castType.
    // ColorCollection lives in the block package even for the Item-typed collections (erased descriptor is
    // the same), so both owners share COLOR_COLLECTION; only the final CHECKCAST type differs.
    private static void registerDyedFields(RetromodTransformer t, String owner, String castType,
                                           String suffix, String collectionField) {
        for (String color : DYE_COLORS) {
            t.registerStaticFieldAccessor(
                    owner, color + "_" + suffix,
                    owner, collectionField, "Lnet/minecraft/world/level/block/ColorCollection;",
                    DYE_COLOR, color, "Lnet/minecraft/world/item/DyeColor;",
                    COLOR_COLLECTION, "pick", "(Lnet/minecraft/world/item/DyeColor;)Ljava/lang/Object;",
                    castType);
        }
    }

    private static final String[] ENTITY_TYPE_CONSTANTS = {
        "ACACIA_BOAT", "ACACIA_CHEST_BOAT", "ALLAY", "AREA_EFFECT_CLOUD", "ARMADILLO",
        "ARMOR_STAND", "ARROW", "AXOLOTL", "BAMBOO_CHEST_RAFT", "BAMBOO_RAFT", "BAT", "BEE",
        "BIRCH_BOAT", "BIRCH_CHEST_BOAT", "BLAZE", "BLOCK_DISPLAY", "BOGGED", "BREEZE",
        "BREEZE_WIND_CHARGE", "CAMEL", "CAMEL_HUSK", "CAT", "CAVE_SPIDER", "CHERRY_BOAT",
        "CHERRY_CHEST_BOAT", "CHEST_MINECART", "CHICKEN", "COD", "COMMAND_BLOCK_MINECART",
        "COPPER_GOLEM", "COW", "CREAKING", "CREEPER", "DARK_OAK_BOAT",
        "DARK_OAK_CHEST_BOAT", "DISPLAY_TRACKING_RANGE", "DOLPHIN", "DONKEY",
        "DRAGON_FIREBALL", "DROWNED", "EGG", "ELDER_GUARDIAN", "ENDERMAN", "ENDERMITE",
        "ENDER_DRAGON", "ENDER_PEARL", "END_CRYSTAL", "EVOKER", "EVOKER_FANGS",
        "EXPERIENCE_BOTTLE", "EXPERIENCE_ORB", "EYE_OF_ENDER", "FALLING_BLOCK", "FIREBALL",
        "FIREWORK_ROCKET", "FISHING_BOBBER", "FOX", "FROG", "FURNACE_MINECART", "GHAST",
        "GIANT", "GLOW_ITEM_FRAME", "GLOW_SQUID", "GOAT", "GUARDIAN", "HAPPY_GHAST",
        "HOGLIN", "HOPPER_MINECART", "HORSE", "HUSK", "ILLUSIONER", "INTERACTION",
        "IRON_GOLEM", "ITEM", "ITEM_DISPLAY", "ITEM_FRAME", "JUNGLE_BOAT",
        "JUNGLE_CHEST_BOAT", "LEASH_KNOT", "LIGHTNING_BOLT", "LINGERING_POTION", "LLAMA",
        "LLAMA_SPIT", "MAGIC_HORSE_WIDTH", "MAGMA_CUBE", "MANGROVE_BOAT",
        "MANGROVE_CHEST_BOAT", "MANNEQUIN", "MARKER", "MINECART", "MOOSHROOM", "MULE",
        "NAUTILUS", "OAK_BOAT", "OAK_CHEST_BOAT", "OCELOT", "OMINOUS_ITEM_SPAWNER",
        "OP_ONLY_CUSTOM_DATA", "PAINTING", "PALE_OAK_BOAT", "PALE_OAK_CHEST_BOAT", "PANDA",
        "PARCHED", "PARROT", "PHANTOM", "PIG", "PIGLIN", "PIGLIN_BRUTE", "PILLAGER",
        "PLAYER", "POLAR_BEAR", "PUFFERFISH", "RABBIT", "RAVAGER", "SALMON", "SHEEP",
        "SHULKER", "SHULKER_BULLET", "SILVERFISH", "SKELETON", "SKELETON_HORSE", "SLIME",
        "SMALL_FIREBALL", "SNIFFER", "SNOWBALL", "SNOW_GOLEM", "SPAWNER_MINECART",
        "SPECTRAL_ARROW", "SPIDER", "SPLASH_POTION", "SPRUCE_BOAT", "SPRUCE_CHEST_BOAT",
        "SQUID", "STRAY", "STRIDER", "TADPOLE", "TEXT_DISPLAY", "TNT", "TNT_MINECART",
        "TRADER_LLAMA", "TRIDENT", "TROPICAL_FISH", "TURTLE", "VEX", "VILLAGER",
        "VINDICATOR", "WANDERING_TRADER", "WARDEN", "WIND_CHARGE", "WITCH", "WITHER",
        "WITHER_SKELETON", "WITHER_SKULL", "WOLF", "ZOGLIN", "ZOMBIE", "ZOMBIE_HORSE",
        "ZOMBIE_NAUTILUS", "ZOMBIE_VILLAGER", "ZOMBIFIED_PIGLIN"
    };

    private static final String[] BLOCK_ENTITY_TYPE_CONSTANTS = {
        "BANNER", "BARREL", "BEACON", "BEEHIVE", "BELL", "BLAST_FURNACE", "BREWING_STAND",
        "BRUSHABLE_BLOCK", "CALIBRATED_SCULK_SENSOR", "CAMPFIRE", "CHEST",
        "CHISELED_BOOKSHELF", "COMMAND_BLOCK", "COMPARATOR", "CONDUIT",
        "COPPER_GOLEM_STATUE", "CRAFTER", "CREAKING_HEART", "DAYLIGHT_DETECTOR",
        "DECORATED_POT", "DISPENSER", "DROPPER", "ENCHANTING_TABLE", "ENDER_CHEST",
        "END_GATEWAY", "END_PORTAL", "FURNACE", "HANGING_SIGN", "HOPPER", "JIGSAW",
        "JUKEBOX", "LECTERN", "MOB_SPAWNER", "OP_ONLY_CUSTOM_DATA", "PISTON",
        "SCULK_CATALYST", "SCULK_SENSOR", "SCULK_SHRIEKER", "SHELF", "SHULKER_BOX", "SIGN",
        "SKULL", "SMOKER", "STRUCTURE_BLOCK", "TEST_BLOCK", "TEST_INSTANCE_BLOCK",
        "TRAPPED_CHEST", "TRIAL_SPAWNER", "VAULT"
    };

}
